#!/bin/sh
#
# Copyright 2005-2011 Nexenta Systems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Installation script generated by bootstrap.sh

PATH=/usr/gnu/bin:/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH

DEBCONF_FRONTEND=noninteractive
DEBCONF_NONINTERACTIVE_SEEN=true
export DEBCONF_FRONTEND DEBCONF_NONINTERACTIVE_SEEN

test "x$1" = x && exit 1
test "x$2" = x && exit 1
test "x$3" = x && exit 1

if test "x$3" = "x1"; then
	mkdir -p /tmp/apt-archive.$$
	mkdir -p $1/var/cache/apt/archives/partial
	mount -F lofs /tmp/apt-archive.$$ $1/var/cache/apt/archives
fi
mkdir -p $1$2
mount -F lofs $2 $1$2


# required.lst and base.lst are symbolic links to the
# selected user profile
export BOOTSTRAP_REQUIRED=$(cat $1/var/tmp/required.lst)
export BOOTSTRAP_BASE=$(cat $1/var/tmp/base.lst)
export APTINST=$(cat $2/aptinst.lst)
export PKGSINST=$(cat $2/pkgs.lst)
LOG="/tmp/install-base-debootstrap.log"
PKGSLOG="/tmp/installed_pkgs.log"

source $2/defaults

echo "Starting ..." >> $LOG
date >> $LOG
cat /etc/issue >> $LOG

chrootenv="/usr/bin/env -i PATH=/usr/gnu/bin:/usr/bin:/sbin:/usr/sbin:/usr/loca/bin:/usr/local/sbin \
LOGNAME=root \
HOME=/root \
TERM=xterm"

TARGET="$1"

PKGSPATH="$2"

PKGS=" \
sunwcsd \
sunwcs \
grep \
sed \
bash \
nexenta-keyring \
debian-archive-keyring \
libreadline6 \
libdb4.6 \
apt-utils \
apt \
coreutils \
package-svr4 \
dpkg \
libgcrypt11 \
libgpg-error0 \
libksba8 \
libpth20 \
libldap-2.4-2 \
gnupg \
gpgv \
libgcc1 \
libgmp3c2 \
liblzma2 \
system-data-keyboard-keytables \
system-library \
system-library-storage-scsi-plugins \
xz-utils \
sysv-rc \
libbz2-1.0 \
lib64bz2-1.0 \
nexenta-ldconfig \
system-library-iconv-utf-8 \
system-library-math \
libstdc++6 \
zlib1g \
lib64z1 \
perl-base \
perl-modules \
perl"

MAINPKGS="\
sunwcsd \
library-libtecla \
service-fault-management \
system-zones \
system-library \
gcc-4.4-base \
libgcc1 \
lib64gcc1 \
zlib1g \
lib64z1 \
system-boot-grub \
system-library-math \
sunwcs \
system-file-system-zfs \
libtspi1 \
libxml2 \
libbz2-1.0 \
package-svr4 \
system-library-install-libinstzones \
dpkg \
perl-base \
debconf \
libssl0.9.8 \
mawk"

function getFile
{
    PKG=$1
    FILE=$PKG"_*.deb"
    PKGFILE=`find $PKGSPATH -name "$FILE"`
    echo "$PKGFILE"
}

function unpack
{
    PKG=$1
    TO=$2
    echo "Unpacking $PKG to $TO ..."
    dpkg-deb -x $PKG $TO
}

function dpkginst
{
    PKG=$2
    echo "Installing $PKG ..."
    chroot $1 $chrootenv dpkg --force-all -i $PKG
}

mkdir -p $TARGET/var/lib/dpkg/updates
mkdir -p $TARGET/var/lib/dpkg/info
mkdir -p $TARGET/var/lib/dpkg/alien
mkdir -p $TARGET/var/lib/dpkg/alternatives
mkdir -p $TARGET/var/lib/dpkg/parts
mkdir -p $TARGET/var/lib/dpkg/triggers

touch $TARGET/var/lib/dpkg/status
touch $TARGET/var/lib/dpkg/available
touch $TARGET/var/lib/dpkg/lock

LPKG=`getFile sunwcsd`
unpack $LPKG $TARGET 2>&1 | tee -a $LOG
LPKG=`getFile sunwcs`
unpack $LPKG $TARGET 2>&1 | tee -a $LOG

for package in $PKGS
do
    if [ "$package" = "sunwcsd" -o "$package" = "sunwcs" ]; then
	continue
    fi

    LPKG=`getFile $package`
    unpack $LPKG $TARGET 2>&1 | tee -a $LOG
done

# hack apt-clone
rm -f $1/etc/apt/apt.conf.d/01nexenta

echo "== 1 - chroot $1 $chrootenv mount -F proc /proc " >> $LOG
chroot $1 $chrootenv mount -F proc /proc 2>&1 | tee -a $LOG

# hack chroot for utils
touch $1/dev/zero

chroot $1 $chrootenv crle -u 2>&1 | tee -a $LOG

echo "deb file:///usr/nexenta/ ${_KS_inst_dist} main contrib non-free" > $1/etc/apt/sources.list

for package in $MAINPKGS
do
    LPKG=`getFile $package`
    dpkginst $1 $LPKG 2>&1 | tee -a $LOG
done

echo "== 2 - chroot $1 $chrootenv mount -F proc /proc " >> $LOG
chroot $1 $chrootenv mount -F proc /proc 2>&1 | tee -a $LOG

echo "== chroot $1 $chrootenv apt-get update" >> $LOG
chroot $1 $chrootenv apt-get update 2>&1 | tee -a $LOG

echo "== chroot $1 $chrootenv apt-get -f -y --force-yes install " >> $LOG
chroot $1 $chrootenv apt-get -f -y --force-yes install 2>&1 | tee -a $LOG

APTCMD="apt-get -o APT::Get::AllowUnauthenticated=1 -o Debug::pkgDPkgProgressReporting=true -o Debug::pkgProblemResolver=true -y --force-yes install"

for package in nexenta-keyring nexenta-ldconfig text-locale; do
	echo "== chroot $1 $chrootenv $APTCMD $package" >> $LOG
	chroot $1 $chrootenv $APTCMD $package 2>&1 | tee -a $LOG
	echo "$package" >> $PKGSLOG
done

echo "== chroot $1 $chrootenv $APTCMD $PKGS" >> $LOG
chroot $1 $chrootenv $APTCMD $PKGS 2>&1 | tee -a $LOG
echo "$PKGS" >> $PKGSLOG

for package in debianutils libusb gzip dialog install-info base-files apt-utils; do
	echo "== chroot $1 $chrootenv $APTCMD $package" >> $LOG
	chroot $1 $chrootenv $APTCMD $package 2>&1 | tee -a $LOG
	echo "$package" >> $PKGSLOG
done

chroot $1 $chrootenv apt-get update 2>&1 | tee -a $LOG
chroot $1 $chrootenv apt-get install -f 2>&1 | tee -a $LOG

echo "== chroot $1 $chrootenv $APTCMD $APTINST" >> $LOG
chroot $1 $chrootenv $APTCMD $APTINST 2>&1 | tee -a $LOG
echo "$APTINST" >> $PKGSLOG

chroot $1 $chrootenv crle -u -l /lib:/usr/lib:/usr/gnu/lib 2>&1 | tee -a $LOG
chroot $1 $chrootenv crle -64 -u -l /lib/64:/usr/lib/64:/usr/gnu/lib/64 2>&1 | tee -a $LOG

chroot $1 $chrootenv apt-get update 2>&1 | tee -a $LOG
chroot $1 $chrootenv dpkg --configure -a 2>&1 | tee -a $LOG
chroot $1 $chrootenv apt-get install -f -y --force-yes 2>&1 | tee -a $LOG

chroot $1 $chrootenv umount /proc 2>&1 | tee -a $LOG

for pid in `ps -ef|awk '/devfsadmd/ {print $2}'`; do
	if pfiles $pid 2>/dev/null | grep $1 >/dev/null; then
		kill -9 $pid 2>/dev/null
		break
	fi
done

sleep 2
umount $1/devices 2>/dev/null
umount -f $1$2 2>/dev/null
if test "x$3" = "x1"; then
	umount -f $1/var/cache/apt/archives
	rm -rf /tmp/apt-archive.$$
fi

cp -f $1/debootstrap/debootstrap.log $1/root
cp $LOG $1/root
cp $PKGSLOG $1/root

# temporary fixes
mkdir -p $1/usr/perl5/bin
cd $1/usr/perl5/bin; ln -sf /usr/bin/perl perl

# fix keyring - need update package nexenta-keyring
chroot $1 touch /usr/share/keyrings/nexenta-archive-removed-keys.gpg

# ntp client config
#NTPCONFCONF="$1/etc/inet/ntp.conf"
#echo "driftfile /etc/inet/ntp.drift" > $NTPCONFCONF
#echo "server pool.ntp.org # default" >> $NTPCONFCONF
#echo "server 0.pool.ntp.org" >> $NTPCONFCONF
#echo "server 1.pool.ntp.org" >> $NTPCONFCONF
#echo "server 2.pool.ntp.org" >> $NTPCONFCONF

exit 0
