#!/bin/bash
LOGFILE="/tmp/nexenta-install.log"
export TERM=ansi
while true; do
	if test ! -f $LOGFILE; then
		sleep 5
		continue
	fi
	tail $LOGFILE >/dev/null 2>&1
	sleep 1
	tail $LOGFILE >/dev/null 2>&1
	tail $LOGFILE >/dev/null 2>&1
	tail.pl -f $LOGFILE
	break
done
